<?php
/**
 * @file
 * content1.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function content1_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Itanagar',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '008b0577-6fdb-47fd-9b8e-04603e112a49',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'bf35e486-dd9e-47bf-827f-6b934d428632',
    ),
  );
  $terms[] = array(
    'name' => 'Kodaikanal',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '02c22498-a979-4019-be09-6dcfb059f283',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'c48d2e19-fed1-4bf8-925d-3f4512a4fcd0',
    ),
  );
  $terms[] = array(
    'name' => 'Shimla',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '06b31b6d-edea-4458-ad8c-83089c765e0f',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '1bfca3e2-5b26-4d9c-9ed4-7d3263df5e3f',
    ),
  );
  $terms[] = array(
    'name' => 'Sikkim',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 85,
    'uuid' => '0b6bee23-b049-426b-b696-0b6e06731f9c',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Hassan',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '0c58959e-1313-40ef-80ea-34f833bf30d2',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '76c5d622-4edc-419d-84ba-c7264c3b09c4',
    ),
  );
  $terms[] = array(
    'name' => 'Gangtok',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0e2ff299-ba87-4a9b-abb2-492ef9ae492c',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '0b6bee23-b049-426b-b696-0b6e06731f9c',
    ),
  );
  $terms[] = array(
    'name' => 'Nagaland',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 90,
    'uuid' => '0f2047e1-7811-4b93-9bcc-7fb47de38e39',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Allahabad',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '10be91ea-69bf-4511-b639-92c6aab023e3',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '97978d24-4942-4b11-b9a9-7b8fbbbd1d50',
    ),
  );
  $terms[] = array(
    'name' => 'Mumbai',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '118dbefc-7135-429a-8713-fb04e550911b',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '5b5568e6-cb8e-42b5-acdc-4d4fd40fa22e',
    ),
  );
  $terms[] = array(
    'name' => 'Mysore',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '14e18713-3909-4fea-8c48-483431d81da9',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '76c5d622-4edc-419d-84ba-c7264c3b09c4',
    ),
  );
  $terms[] = array(
    'name' => 'Nagpur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '155063d1-4857-4d4f-9ed2-1ef5a79b716b',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '5b5568e6-cb8e-42b5-acdc-4d4fd40fa22e',
    ),
  );
  $terms[] = array(
    'name' => 'Cochin',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '1965fe5c-3d14-47d9-a04b-7510942af68f',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'fe5479f2-fc17-471f-95ce-2f72251326d2',
    ),
  );
  $terms[] = array(
    'name' => 'Mizoram',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 91,
    'uuid' => '1a4fd839-c76b-42b2-84b1-1d680699af0f',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Kovalam',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '1b8ca594-80c0-49a1-bb65-ec25429af86e',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'fe5479f2-fc17-471f-95ce-2f72251326d2',
    ),
  );
  $terms[] = array(
    'name' => 'Himachal Pradesh',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 99,
    'uuid' => '1bfca3e2-5b26-4d9c-9ed4-7d3263df5e3f',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Darjeeling',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '1d8ce31e-6655-4df3-b839-b7f5d99d148b',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '21b640f7-d19b-49cf-9c49-5066c2bb61fe',
    ),
  );
  $terms[] = array(
    'name' => 'Tirupati',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '1dfa96b0-4d2b-4fc8-8c1d-8bdcafb3db95',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'd8ce61ce-49b0-41c7-8af5-0043bf4902f6',
    ),
  );
  $terms[] = array(
    'name' => 'Hampi',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '1e4f73bb-6557-4a65-8e52-7e6eb3b3c1c7',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '76c5d622-4edc-419d-84ba-c7264c3b09c4',
    ),
  );
  $terms[] = array(
    'name' => 'Gurgaon',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1e6e6d99-d229-4ae7-bfa3-ca2d9653ecb3',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '2ca4c829-3cfb-4b3a-a76c-b4418cd0bbfa',
    ),
  );
  $terms[] = array(
    'name' => 'Jammu',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '1fa03a79-52db-43a6-9408-f12ba06e1ddd',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'f973ec00-eb58-4a58-89dc-16ed40e9d028',
    ),
  );
  $terms[] = array(
    'name' => 'Rameshwaram',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => '208354e1-066c-4117-ae70-2f460829a5a0',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'c48d2e19-fed1-4bf8-925d-3f4512a4fcd0',
    ),
  );
  $terms[] = array(
    'name' => 'West Bengal',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '21b640f7-d19b-49cf-9c49-5066c2bb61fe',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Trichy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => '228b69a6-e5a6-43fb-a074-8a04cccf7c9c',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'c48d2e19-fed1-4bf8-925d-3f4512a4fcd0',
    ),
  );
  $terms[] = array(
    'name' => 'Rishikesh',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '23f16bdb-678f-445b-a318-470a0cbedd39',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '36132bd2-5d88-4bd3-b596-d31287fdca3b',
    ),
  );
  $terms[] = array(
    'name' => 'Gaya',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '26e27870-9184-407d-b23c-e5093b3f3373',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e4f308a7-b52b-4b6f-bca0-c7804740dc02',
    ),
  );
  $terms[] = array(
    'name' => 'Bundi',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '2aba40d8-539c-4cfd-b3eb-b83384659c93',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '6c7206b7-9bfb-4d61-9825-b31adf92219c',
    ),
  );
  $terms[] = array(
    'name' => 'Jaisalmer',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '2beca401-144b-43f3-925b-a1dd48893bd3',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '6c7206b7-9bfb-4d61-9825-b31adf92219c',
    ),
  );
  $terms[] = array(
    'name' => 'Agra',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2c908121-ab99-452c-a710-f631ac5d3d71',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '97978d24-4942-4b11-b9a9-7b8fbbbd1d50',
    ),
  );
  $terms[] = array(
    'name' => 'Haryana',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 100,
    'uuid' => '2ca4c829-3cfb-4b3a-a76c-b4418cd0bbfa',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Amritsar',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2e185a2d-053e-49b0-b893-3d8b5ac734a2',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'ec690920-18e1-4840-bff6-8f89c70f320e',
    ),
  );
  $terms[] = array(
    'name' => 'Dispur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2e2bbb50-7415-4ff5-be34-427873a8da5d',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '60e82bd6-6c3f-4a75-af20-9f841c74349a',
    ),
  );
  $terms[] = array(
    'name' => 'Bhopal',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '2f57976f-702b-4410-98b5-bb458a9574cf',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '5d8a13a9-ae26-44a3-b8cf-1ef1d36c21d0',
    ),
  );
  $terms[] = array(
    'name' => 'Patna',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '31dea72e-0de3-457c-a166-81b3ab2aeee5',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e4f308a7-b52b-4b6f-bca0-c7804740dc02',
    ),
  );
  $terms[] = array(
    'name' => 'New Delhi',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3421ef24-660c-4211-b969-1d665194d841',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '653721d2-b159-4f60-8108-ced99c408880',
    ),
  );
  $terms[] = array(
    'name' => 'Ajmer',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3435ac48-583c-4c6d-8992-063ac41e9869',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '6c7206b7-9bfb-4d61-9825-b31adf92219c',
    ),
  );
  $terms[] = array(
    'name' => 'Shillong',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '34c680e0-fe8a-43a2-95bb-f3c68528424e',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '5368e0c2-60c1-47d8-9c81-e3848ba13c52',
    ),
  );
  $terms[] = array(
    'name' => 'Uttaranchal',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 73,
    'uuid' => '36132bd2-5d88-4bd3-b596-d31287fdca3b',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Kolkata',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '3d96a072-a79f-46dc-894b-2ddc1d0d600a',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '21b640f7-d19b-49cf-9c49-5066c2bb61fe',
    ),
  );
  $terms[] = array(
    'name' => 'Jharkhand',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 98,
    'uuid' => '401b9822-4925-48d4-bb4c-dd29c2cc6686',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Udupi',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '4e520335-88d4-476c-b6ce-d94584ec4610',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '76c5d622-4edc-419d-84ba-c7264c3b09c4',
    ),
  );
  $terms[] = array(
    'name' => 'Patiala',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '4f3b0d01-f5a4-4d9f-bd14-89b3a6a0b02e',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'ec690920-18e1-4840-bff6-8f89c70f320e',
    ),
  );
  $terms[] = array(
    'name' => 'Jamshedpur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4f701083-5b77-4a49-a002-153d05de7a38',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '401b9822-4925-48d4-bb4c-dd29c2cc6686',
    ),
  );
  $terms[] = array(
    'name' => 'Vijayawada',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '5046068b-8b03-43e2-a324-e3af3eba3b05',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'd8ce61ce-49b0-41c7-8af5-0043bf4902f6',
    ),
  );
  $terms[] = array(
    'name' => 'Coimbatore',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '50a308f3-be1a-4dd8-b8d6-e75664972e17',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'c48d2e19-fed1-4bf8-925d-3f4512a4fcd0',
    ),
  );
  $terms[] = array(
    'name' => 'Trivandrum',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => '50d23167-3a78-433f-8110-8d71da162227',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'fe5479f2-fc17-471f-95ce-2f72251326d2',
    ),
  );
  $terms[] = array(
    'name' => 'Old Goa',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '518bff2c-d9ee-4d62-91da-debad96eb19e',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e556f043-7b78-48f8-95d9-7117bce4f4ea',
    ),
  );
  $terms[] = array(
    'name' => 'Meghalaya',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 92,
    'uuid' => '5368e0c2-60c1-47d8-9c81-e3848ba13c52',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Faridabad',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '53a1a4b3-3ca9-43f9-99fa-2f5a3ac4bc9e',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '2ca4c829-3cfb-4b3a-a76c-b4418cd0bbfa',
    ),
  );
  $terms[] = array(
    'name' => 'Konark',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '5620e6f7-1d5c-4ecf-9000-48ac2255efff',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '76cccc55-f338-4b0f-9df2-a0a4c571d1c2',
    ),
  );
  $terms[] = array(
    'name' => 'Maharashtra',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 94,
    'uuid' => '5b5568e6-cb8e-42b5-acdc-4d4fd40fa22e',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Manipur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 93,
    'uuid' => '5d1fb207-975e-48ce-b633-56bc5cb23245',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Madhya Pradesh',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 95,
    'uuid' => '5d8a13a9-ae26-44a3-b8cf-1ef1d36c21d0',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Varanasi',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '5dce3ca5-9e64-4307-98b1-2d0a5bb3c2f2',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '97978d24-4942-4b11-b9a9-7b8fbbbd1d50',
    ),
  );
  $terms[] = array(
    'name' => 'Assam',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 120,
    'uuid' => '60e82bd6-6c3f-4a75-af20-9f841c74349a',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Thekkady',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => '62a20b7e-6d07-4d0d-9c0b-db473fbdfaab',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'fe5479f2-fc17-471f-95ce-2f72251326d2',
    ),
  );
  $terms[] = array(
    'name' => 'Delhi',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 110,
    'uuid' => '653721d2-b159-4f60-8108-ced99c408880',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Canacona',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '653e7142-4d03-4b8d-835c-4e81064b890b',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e556f043-7b78-48f8-95d9-7117bce4f4ea',
    ),
  );
  $terms[] = array(
    'name' => 'Alwar',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '67cdce5a-5521-4947-b6e9-e08dc11142a0',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '6c7206b7-9bfb-4d61-9825-b31adf92219c',
    ),
  );
  $terms[] = array(
    'name' => 'Ahmedabad',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '694c2bc5-ed20-4b0f-8d6f-311ce0e4df33',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '73cb98bf-cf56-4110-a55a-c875f7a63849',
    ),
  );
  $terms[] = array(
    'name' => 'Others',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 88,
    'uuid' => '6bc71bad-3b4e-464f-9166-379b75c48df3',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Rajasthan',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 86,
    'uuid' => '6c7206b7-9bfb-4d61-9825-b31adf92219c',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Manali',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '6ce69732-b854-4568-9fff-543cd50454a3',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '1bfca3e2-5b26-4d9c-9ed4-7d3263df5e3f',
    ),
  );
  $terms[] = array(
    'name' => 'Munnar',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '6dfe9bf1-6af7-40d8-b227-7e22b0d5d31b',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'fe5479f2-fc17-471f-95ce-2f72251326d2',
    ),
  );
  $terms[] = array(
    'name' => 'Warangal',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '6ea120ca-fdc8-4d0e-84ef-f2fac011c170',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'd8ce61ce-49b0-41c7-8af5-0043bf4902f6',
    ),
  );
  $terms[] = array(
    'name' => 'Guwahati',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '6f0fa279-4408-4e26-971b-882e41aa2012',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '60e82bd6-6c3f-4a75-af20-9f841c74349a',
    ),
  );
  $terms[] = array(
    'name' => 'Ranchi',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '7026a4a9-60f8-4865-ae47-ab0d93e74aac',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '401b9822-4925-48d4-bb4c-dd29c2cc6686',
    ),
  );
  $terms[] = array(
    'name' => 'Vaishali',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '70ca3347-36c1-49e0-ba2f-25dd3dff5ab6',
    'vocabulary_machine_name' => 'state_city',
    'parent' => array(
      0 => 'e4f308a7-b52b-4b6f-bca0-c7804740dc02',
    ),
  );
  $terms[] = array(
    'name' => 'Gujarat',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 101,
    'uuid' => '73cb98bf-cf56-4110-a55a-c875f7a63849',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Margao',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '75d9db12-49e8-4788-ad8b-4419192a3386',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e556f043-7b78-48f8-95d9-7117bce4f4ea',
    ),
  );
  $terms[] = array(
    'name' => 'karnataka',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 137,
    'uuid' => '76c5d622-4edc-419d-84ba-c7264c3b09c4',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Odisha',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 132,
    'uuid' => '76cccc55-f338-4b0f-9df2-a0a4c571d1c2',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Quilon',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => '78e68c24-7d45-4c0d-83d3-656085cf80c5',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'fe5479f2-fc17-471f-95ce-2f72251326d2',
    ),
  );
  $terms[] = array(
    'name' => 'Pahalgam',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '7d2417f8-9bb5-4893-8cc7-6d114d274687',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'f973ec00-eb58-4a58-89dc-16ed40e9d028',
    ),
  );
  $terms[] = array(
    'name' => 'Dharamsala',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7e7fd826-c454-48d9-a6f5-2f24b963b931',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '1bfca3e2-5b26-4d9c-9ed4-7d3263df5e3f',
    ),
  );
  $terms[] = array(
    'name' => 'Murshidabad',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '807ee735-e436-42a2-b915-a777f3fecb5c',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '21b640f7-d19b-49cf-9c49-5066c2bb61fe',
    ),
  );
  $terms[] = array(
    'name' => 'Rajgir',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '83a39c03-72c4-4b8d-9e9e-8af822839d65',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e4f308a7-b52b-4b6f-bca0-c7804740dc02',
    ),
  );
  $terms[] = array(
    'name' => 'Puri',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '83b0bcba-dd12-4d3d-9a8f-ad0be1b51f7d',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '76cccc55-f338-4b0f-9df2-a0a4c571d1c2',
    ),
  );
  $terms[] = array(
    'name' => 'Pondicherry',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '85c0d494-dfaf-464e-a979-fb292c12d521',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'd7a0f688-28b7-4523-8beb-b170f3e0fb1f',
    ),
  );
  $terms[] = array(
    'name' => 'Tripura',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 79,
    'uuid' => '8aa3a8eb-e291-41e4-8c7b-d4bc4b08f379',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Tezpur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '8c98770b-246c-4c05-a1c9-a2efffcfc17e',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '60e82bd6-6c3f-4a75-af20-9f841c74349a',
    ),
  );
  $terms[] = array(
    'name' => 'Aurangabad',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '907c4ff5-5e43-4f05-9b45-e185ec43d3d8',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '5b5568e6-cb8e-42b5-acdc-4d4fd40fa22e',
    ),
  );
  $terms[] = array(
    'name' => 'Kanyakumari',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '920c918e-353d-4afe-9907-05967a12fffd',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'c48d2e19-fed1-4bf8-925d-3f4512a4fcd0',
    ),
  );
  $terms[] = array(
    'name' => 'Surat',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '921c3e7b-0315-4ef8-8e32-8a1eb71625ee',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '73cb98bf-cf56-4110-a55a-c875f7a63849',
    ),
  );
  $terms[] = array(
    'name' => 'Uttar Pradesh',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 75,
    'uuid' => '97978d24-4942-4b11-b9a9-7b8fbbbd1d50',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Agartala',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9c8d997d-0946-4ff7-bce0-4c276e608e32',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '8aa3a8eb-e291-41e4-8c7b-d4bc4b08f379',
    ),
  );
  $terms[] = array(
    'name' => 'Haridwar',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '9ed17697-76c8-487f-8bf6-ad5d1d40e09f',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '36132bd2-5d88-4bd3-b596-d31287fdca3b',
    ),
  );
  $terms[] = array(
    'name' => 'Nainital',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '9f7a3a28-73c4-42d7-a6ce-e119d70137cd',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '36132bd2-5d88-4bd3-b596-d31287fdca3b',
    ),
  );
  $terms[] = array(
    'name' => 'Gandhinagar',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a2e58ccc-ae3d-4fe4-b9a4-61b9d6e7b9da',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '73cb98bf-cf56-4110-a55a-c875f7a63849',
    ),
  );
  $terms[] = array(
    'name' => 'Madurai',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'a4c2c4de-80e1-4a04-aa46-2539b2057a16',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'c48d2e19-fed1-4bf8-925d-3f4512a4fcd0',
    ),
  );
  $terms[] = array(
    'name' => 'Ludhiana',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'a751dcd3-8b0e-45e9-87d3-8157649cd3e4',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'ec690920-18e1-4840-bff6-8f89c70f320e',
    ),
  );
  $terms[] = array(
    'name' => 'Visakhapatnam',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'a9f6a11f-e9d0-4e0d-90aa-6cb4670dd6fd',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'd8ce61ce-49b0-41c7-8af5-0043bf4902f6',
    ),
  );
  $terms[] = array(
    'name' => 'Kullu',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'ac39e0e1-db86-40e4-baa5-47ec22023438',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '1bfca3e2-5b26-4d9c-9ed4-7d3263df5e3f',
    ),
  );
  $terms[] = array(
    'name' => 'Leh',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'b18f7156-b5f4-4faa-b33e-fe31c0fbbe1a',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'f973ec00-eb58-4a58-89dc-16ed40e9d028',
    ),
  );
  $terms[] = array(
    'name' => 'Chandigarh',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'b24f5a40-6a36-471f-a63d-61ad1916bad6',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'ec690920-18e1-4840-bff6-8f89c70f320e',
    ),
  );
  $terms[] = array(
    'name' => 'Shekhawati',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => 'b2a01ab0-3f4a-4cbf-906c-bb092cb4ed59',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '6c7206b7-9bfb-4d61-9825-b31adf92219c',
    ),
  );
  $terms[] = array(
    'name' => 'Chhattisgarh',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 112,
    'uuid' => 'b3d9dd2f-8866-4c05-8412-9551642b0890',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Bikaner',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'b4c4b542-fbb4-465f-aafa-fe9421cebbd5',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '6c7206b7-9bfb-4d61-9825-b31adf92219c',
    ),
  );
  $terms[] = array(
    'name' => 'Burdwan',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b711854f-42b6-45ee-b9a1-9b592a2c52fb',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '21b640f7-d19b-49cf-9c49-5066c2bb61fe',
    ),
  );
  $terms[] = array(
    'name' => 'Durgapur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'be98df22-f798-4457-a36f-77693c754bb5',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '21b640f7-d19b-49cf-9c49-5066c2bb61fe',
    ),
  );
  $terms[] = array(
    'name' => 'Arunachal Pradesh',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 124,
    'uuid' => 'bf35e486-dd9e-47bf-827f-6b934d428632',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Khajuraho',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'bfae3cd9-5ca8-4568-ab2f-c9ac8b258d2d',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '5d8a13a9-ae26-44a3-b8cf-1ef1d36c21d0',
    ),
  );
  $terms[] = array(
    'name' => 'Dehradun',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c28a10f0-c57d-482d-bfef-613c33af0a8b',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '36132bd2-5d88-4bd3-b596-d31287fdca3b',
    ),
  );
  $terms[] = array(
    'name' => 'Aizawl',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c3829c3d-d521-4c7c-91d7-56f597c12b89',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '1a4fd839-c76b-42b2-84b1-1d680699af0f',
    ),
  );
  $terms[] = array(
    'name' => 'Tamil Nadu',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 84,
    'uuid' => 'c48d2e19-fed1-4bf8-925d-3f4512a4fcd0',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Udaipur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 9,
    'uuid' => 'c84830e6-c685-439e-941e-0e46ab12a292',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '6c7206b7-9bfb-4d61-9825-b31adf92219c',
    ),
  );
  $terms[] = array(
    'name' => 'Jodhpur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => 'c9701ecb-9391-44d1-a17d-f2d116c01f1f',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '6c7206b7-9bfb-4d61-9825-b31adf92219c',
    ),
  );
  $terms[] = array(
    'name' => 'Bhubaneswar',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cba5bb63-0424-4302-8e79-2a73ba15eebe',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '76cccc55-f338-4b0f-9df2-a0a4c571d1c2',
    ),
  );
  $terms[] = array(
    'name' => 'Vasco Da Gama',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => 'ccd5cca5-14e6-4be2-9c77-fd216ce80156',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e556f043-7b78-48f8-95d9-7117bce4f4ea',
    ),
  );
  $terms[] = array(
    'name' => 'Dhanbad',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'cdde8c15-8163-414d-814c-9a30da361a2a',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '401b9822-4925-48d4-bb4c-dd29c2cc6686',
    ),
  );
  $terms[] = array(
    'name' => 'Jaipur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'd1312c75-2400-4b99-b69e-ce5025d61fa8',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '6c7206b7-9bfb-4d61-9825-b31adf92219c',
    ),
  );
  $terms[] = array(
    'name' => 'Kohima',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd5253d27-c2cd-47de-9207-24f7c9cfcabe',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '0f2047e1-7811-4b93-9bcc-7fb47de38e39',
    ),
  );
  $terms[] = array(
    'name' => 'Thanjavur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => 'd739ecc3-b74f-45f5-98d8-8b6e2a6d25e1',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'c48d2e19-fed1-4bf8-925d-3f4512a4fcd0',
    ),
  );
  $terms[] = array(
    'name' => 'Pondicherry',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 89,
    'uuid' => 'd7a0f688-28b7-4523-8beb-b170f3e0fb1f',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Panaji',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'd7a72d45-36bf-43f8-8ec5-2ee208dd91ad',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e556f043-7b78-48f8-95d9-7117bce4f4ea',
    ),
  );
  $terms[] = array(
    'name' => 'Manipur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'd8c84a0d-64ee-443d-a2a8-00f62f9e820d',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '73cb98bf-cf56-4110-a55a-c875f7a63849',
    ),
  );
  $terms[] = array(
    'name' => 'Andhra Pradesh',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 126,
    'uuid' => 'd8ce61ce-49b0-41c7-8af5-0043bf4902f6',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Gulmarg',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd9f60407-eeef-4f92-a3eb-a6e630c99fc1',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'f973ec00-eb58-4a58-89dc-16ed40e9d028',
    ),
  );
  $terms[] = array(
    'name' => 'Nalanda',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'dbac6760-b876-4ff1-9148-ec86f5b6d999',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e4f308a7-b52b-4b6f-bca0-c7804740dc02',
    ),
  );
  $terms[] = array(
    'name' => 'Lucknow',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'dcc7488d-5642-4e66-9d0c-9677a58225a3',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '97978d24-4942-4b11-b9a9-7b8fbbbd1d50',
    ),
  );
  $terms[] = array(
    'name' => 'Chennai',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'df20e798-d5b7-4d2f-9e57-fb9f14ba630e',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'c48d2e19-fed1-4bf8-925d-3f4512a4fcd0',
    ),
  );
  $terms[] = array(
    'name' => 'Vadodara',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'e2a244de-315b-49a7-9936-86acb1af99b3',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '73cb98bf-cf56-4110-a55a-c875f7a63849',
    ),
  );
  $terms[] = array(
    'name' => 'Bihar',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 114,
    'uuid' => 'e4f308a7-b52b-4b6f-bca0-c7804740dc02',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Hyderabad',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e528fa31-83a6-4198-a1c6-7ed90e2b28fb',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'd8ce61ce-49b0-41c7-8af5-0043bf4902f6',
    ),
  );
  $terms[] = array(
    'name' => 'Goa',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 102,
    'uuid' => 'e556f043-7b78-48f8-95d9-7117bce4f4ea',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Pune',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'e8cd3f79-e57e-4454-ace7-14f48609e0e0',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '5b5568e6-cb8e-42b5-acdc-4d4fd40fa22e',
    ),
  );
  $terms[] = array(
    'name' => 'Indore',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'e8fb5132-229a-48ff-89d1-6d253f6a6947',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '5d8a13a9-ae26-44a3-b8cf-1ef1d36c21d0',
    ),
  );
  $terms[] = array(
    'name' => 'Gwalior',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'e9481eb9-38ad-4bca-86c0-47cf2fb3ab3c',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '5d8a13a9-ae26-44a3-b8cf-1ef1d36c21d0',
    ),
  );
  $terms[] = array(
    'name' => 'Raipur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e9a8973f-cbb0-4fb4-af9d-1446831b8ab1',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'b3d9dd2f-8866-4c05-8412-9551642b0890',
    ),
  );
  $terms[] = array(
    'name' => 'Mapusa',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'ea1bfa81-7b05-4105-97b8-b5b412c8a75c',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e556f043-7b78-48f8-95d9-7117bce4f4ea',
    ),
  );
  $terms[] = array(
    'name' => 'Punjab',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 87,
    'uuid' => 'ec690920-18e1-4840-bff6-8f89c70f320e',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Orchha',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ec693a81-2a2c-4307-9116-7dd357dba601',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '5d8a13a9-ae26-44a3-b8cf-1ef1d36c21d0',
    ),
  );
  $terms[] = array(
    'name' => 'Cuttack',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'ed1e94e3-946b-49fd-a259-2a4f4c9e19e0',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '76cccc55-f338-4b0f-9df2-a0a4c571d1c2',
    ),
  );
  $terms[] = array(
    'name' => 'Kumarakom',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'ee6f84ed-c518-4950-932c-2394aa5ef6f6',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'fe5479f2-fc17-471f-95ce-2f72251326d2',
    ),
  );
  $terms[] = array(
    'name' => 'Ooty',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => 'efffacce-a691-4c5f-9ea0-deaf006c9b5c',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'c48d2e19-fed1-4bf8-925d-3f4512a4fcd0',
    ),
  );
  $terms[] = array(
    'name' => 'Kozhikode',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'f4683648-4f62-49de-8901-a389d21d1a54',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'fe5479f2-fc17-471f-95ce-2f72251326d2',
    ),
  );
  $terms[] = array(
    'name' => 'Ladakh',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'f7b8f41b-b6ad-463d-ae5b-fa4c62b5a3a3',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'f973ec00-eb58-4a58-89dc-16ed40e9d028',
    ),
  );
  $terms[] = array(
    'name' => 'Jammu and Kashmir',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 97,
    'uuid' => 'f973ec00-eb58-4a58-89dc-16ed40e9d028',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Ponda',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => 'fa1771eb-025f-4f01-a7a0-72a5187af5b8',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'e556f043-7b78-48f8-95d9-7117bce4f4ea',
    ),
  );
  $terms[] = array(
    'name' => 'Ranakpur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => 'fade89b3-4ece-4d48-958f-6971bbd114cd',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '6c7206b7-9bfb-4d61-9825-b31adf92219c',
    ),
  );
  $terms[] = array(
    'name' => 'Bangalore',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'fbbf6afe-a6c7-47f8-8def-b22444b3cd4a',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '76c5d622-4edc-419d-84ba-c7264c3b09c4',
    ),
  );
  $terms[] = array(
    'name' => 'Imphal',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'fc63566a-a92d-49d9-a5dd-fd33534b5efa',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => '5d1fb207-975e-48ce-b633-56bc5cb23245',
    ),
  );
  $terms[] = array(
    'name' => 'Alleppey',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'fdf6a6ea-18f7-4366-b91e-04bc70d8efa3',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
    'parent' => array(
      0 => 'fe5479f2-fc17-471f-95ce-2f72251326d2',
    ),
  );
  $terms[] = array(
    'name' => 'Kerala',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 96,
    'uuid' => 'fe5479f2-fc17-471f-95ce-2f72251326d2',
    'vocabulary_machine_name' => 'state_city',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  return $terms;
}
